### ISSUE TITLE
Gestión de credenciales

### ISSUE THREAD

**Issue by aaramirez** [synergyvision/expedientedigital#3]
- [x] Gestionar la recuperación de clave perdida utilizando los mecanismos provistos por Firebase.
- [x] Desarrollar la funcionalidad de cambio de clave.

**Comment by michellealleyne** [comment]
1. Recuperación de clave perdida:
A través del mecanismo proporcionado por Firebase, una vez que el usuario coloque su correo electrónico para realizar el cambio de contraseña, será enviado un email el cual contendrá un enlace hacia la siguiente ruta: `http:localhost:4200`. Esta ruta se encuentra protegida, por lo que sólo si dicho enlace es válido, el usuario podrá proceder a cambiar su contraseña. 

2.  Desarrollar la funcionalidad de cambio de clave.
Esta funcionalidad se encuentra momentáneamente en el  _Dashboard_ de la aplicación. Cómo método de seguridad,  el usuario debe proveer su contraseña actual para proceder con el cambio de credenciales.
