### ISSUE TITLE
Configuración de la base de datos

### ISSUE THREAD

**Issue by aaramirez** [synergyvision/expedientedigital#4]
- [x] Configuración de la Base de datos Firebase para utilizar Email y Clave.
- [x] Configuración de la permisología de acceso a la Base de Datos.

**Comment by michellealleyne** [comment]
- Se configuró el método de autentificación de usuarios en _Firebase Authentication_  a través de correo electrónico y contraseña.
- Los permisos configurados sobre la base de datos son sobre las operaciones de escritura:  sólo se puede escribir en la base de datos si el usuario ha iniciado sesión y además, es dueño del documento.

![image](https://user-images.githubusercontent.com/63029075/91243074-11f8bf00-e717-11ea-9080-5b9f46d41d5d.png)

- Se configuraron los permisos sobre _Firebase Storage_, por lo que: solo se puede crear, actualizar, eliminar documentos si el usuario  ha iniciado sesión y además, es dueño de la información.

![image](https://user-images.githubusercontent.com/63029075/91243168-4ff5e300-e717-11ea-84aa-1a9b8dcd399f.png)
